/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mike' at '10/22/16 4:06 PM' with Gradle 2.10
 *
 * @author mike, @date 10/22/16 4:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
